/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hnefatafl' at '2/1/17 11:12 AM' with Gradle 2.14.1
 *
 * @author hnefatafl, @date 2/1/17 11:12 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
